{% set name = "apischema" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wyfo/apischema/archive/v{{ version }}.tar.gz
  sha256: 96a56509a8f8d61cbb3f1fe49e21e6b5e4909938f4e21157ea5a58c8920c944d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
  run_constrained:
    # The following is needed for the (optional) apischema.graphql to work properly:
    - graphql-core >=3.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - apischema

about:
  home: https://github.com/wyfo/apischema
  doc_url: https://wyfo.github.io/apischema
  dev_url: https://github.com/wyfo/apischema
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: JSON (de)serialization, GraphQL and JSON schema generation using Python typing.

extra:
  recipe-maintainers:
    - klauer
    - wyfo
